# Generated by Django 5.1.1 on 2024-10-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_modelmessage_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
    ]
