# Generated by Django 5.1.1 on 2024-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_modelmessage_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmessage',
            name='parts',
            field=models.JSONField(),
        ),
    ]
